file_format: '1'
id: charybdis
name: Charybdis
type: shield
url: https://github.com/ergonautkb/one
requires: [nrfmicro_13]
features:
  - keys
  - pointer
siblings:
  - charybdis_left
  - charybdis_right
